### ISSUE TITLE
Audio and other drivers for Hapanero pre-EB2

### ISSUE THREAD

**Issue by PC-DOS** [gus33000/MSM8994-8992-NT-ARM64-Drivers#10]
In recent tests, we've found that  some drivers provided for Hapanero EB2 and/or 950XL, including audio drivers, can be directly applied to Hapanero pre-EB2.

However, the SD card may still don't work, inserting a card has no reactions. I'm not sure if it's caused by qcPEP or something else as I can't find a WP extraced from pre-EB2 Hapaneroes with a SD card support (parameters for SDC2 seems to be missing from the registry, and those for SDC1 looks strange). BSOD with SDBUS_INTERNAL_ERROR is also a common problem.

These tests were done with 1902 drives, on Win10 17134. Drivers used for testing can be found at [This Repo](https://github.com/PC-DOS/RX-130-EB1.0-Win10-ARM64/tree/testing), 'Testing 20190216' and 'Testing 20190305' works better . Using drivers provided with 1903 or 1904(main branch) may run into some problems including BSOD, weird Wi-Fi or GPU behavior, etc. We are still testing, but finding a resolution may be hard for us.

Thanks a lot!

**Comment by cleveHEX** [comment]
I don't know much about those drivers, my answer might not be accurate/relevant, but IIRC drivers are same for all devices (exceptions apply), just some of them may have tweaks for specific device.

**Comment by woachk** [comment]
@PC-DOS for Hapanero EB2, problems are present with drivers that depend on qcsubsys. Other drivers that do not depend on subsys can work, will actualize that info later too.

**Comment by gus33000** [comment]
@PC-DOS It's normal for you to get issues with EB2 drivers as QcSubsys won't work nicely on Cobalt 1 SoCs (such as MSM8994AA) I agree there's room for improvements regarding EB1, but due to a lack of a testing device I can't make much progress on that. I'll probably see with @woachk when he's free about that (and when I'm free too). Looked quickly at your repo, some drivers you install are either not needed or won't work as is. We'll clarify more later (when we will have time). For now keep in mind audio requires subsys without it it won't work. I also saw you tried to install some inbox windows drivers, I don't understand at all why..

You can look at the updated 1904 branch to see a better sorting of drivers as well to get an idea of what belongs to what as well.

I would appreciate if you could make a structure like we do for drivers so we get a clear idea of what works out based on the 1904 branch using the same folder names and drivers, would be easier for us than having to look at folders picked from driverstore (including stock windows drivers that shouldn't even be here in the first place..)

**Comment by PC-DOS** [comment]
@gus33000 The driver tree in my repo was created by an all-in-one tool (Dism++) and I haven't organized them (for faster testing). I apologize for that.

The inbox drivers were used for some early tests and they are not included in recent tests. As in early tests, the Windows (with no third party drivers deployed) will crash before OOBE. Please ignore these inbox drivers...

QcSubSys, as well as audio, was successfully launched on 17134 with drivers from the February version of this driver package. Tmsix (Mr. Chen) told me that he will (or already have) send the OS image to you along with an EB1 Hapanero for testing.

**Comment by woachk** [comment]
@PC-DOS is your EB1 HWID1000 or a later revision?

**Comment by PC-DOS** [comment]
@woachk Yes, its HWID is 1000

**Comment by gus33000** [comment]
![image](https://user-images.githubusercontent.com/3755345/57526325-68c56400-732d-11e9-96e8-2ec60425daef.png)
Issue is being dealt with ;)

**Comment by gus33000** [comment]
Problem resolved, please use the 1905-pre branch for Hapanero EB1.
Inject  MSM8994 folder as well as Device Specifics\Hapanero\EB1 and Device Specifics\MMO to get feature parity with EB2 RX130. Everything works the same including cellular. To get GPU to work install under remote desktop the drivers provided under "QcomPkg - EB1 - Install From RDP"
