### ISSUE TITLE
[950XL Single Sim] Sim Card Not Detected.

### ISSUE THREAD

**Issue by ghost** [gus33000/MSM8994-8992-NT-ARM64-Drivers#13]
The Mobile device status is showing "Account Not Active" When trying to use my EE Sim card.

**Comment by cleveHEX** [comment]
Celluar does not work yet.

**Comment by cleveHEX** [comment]
I thought this is deployer repo for some reason, reopening as I am not supposed to close issues here.

**Comment by woachk** [comment]
@CornyjK issue will be closed soon anyway, cellular is up but that isn't pushed here yet.

**Comment by cleveHEX** [comment]
> 
> 
> @CornyjK issue will be closed soon anyway, cellular is up but that isn't pushed here yet.

I know, I have seen the great efforts and the result.

**Comment by ghost** [comment]
If you guys manage to get the mobile side fully working as well as the gps and the cameras functioning. I'd throw out wp10 altogether!

**Comment by gus33000** [comment]
GPS works already since a while on 950 XL, Hapanero devices.  Camera is on the todo list but we can't say for sure if they will ever work. Cellular has been brought up already but issues exist. As issues exists still even though sim cards are detected, I'm not going to close this issue until that's dealt with. See #11 for one of the issues.

**Comment by ghost** [comment]
Nice to hear. Any updates on the sound volume fix?

**Comment by gus33000** [comment]
Sound is a bit tricky, so for now, no no updates on that
