### ISSUE TITLE
Cellular doesn't work on >= 18912 due to breaking WWAN API changes

### ISSUE THREAD

**Issue by gus33000** [gus33000/MSM8994-8992-NT-ARM64-Drivers#24]
Our cellular stack relied on Windows Phone networking stack being still present on Windows 10. By build 18912 the stack has been removed. Cellular won't work anymore if we don't migrate to the Desktop networking stack.

**Comment by quiret** [comment]
Dear gus33000. Do you have insight about the transformability of the old Phone Networking Stack to the Desktop Networking Stack? Can all the features of the Phone Stack be redirected to the Desktop Stack? If not what API calls went missing that ought to be required? Are those documented somewhere?

**Comment by falkor2k15** [comment]
Does this help in an ARM64 context?
https://www.youtube.com/watch?v=hWxA6KdTjjY

**Comment by quiret** [comment]
HUGE NEWS: cellular does work again thanks to gus33000's WMRil efforts! https://twitter.com/gus33000/status/1189243064969256965 He tested it using build 19008.1

EDIT: there still appears to be an issue with OS communication with the new RIL stuff: https://twitter.com/gus33000/status/1189560530761060353 hopefully gus can fix it.

EDIT: so this issue can be closed because of gus33000's latest tweet: https://twitter.com/gus33000/status/1189839204534095874
